### ISSUE TITLE
Sehr Gut

### ISSUE THREAD

**Issue by ghost** [tim03we/AdvancedBan#1]
(Sry das ich das als Issue mache)
Aber kannst du evt. machen das man eigene IDs in der config.yml hinzufügen kann, und man das format des Bannes also wenn man versucht zu joinen auch ändern kann?
Danke

**Comment by tim03we** [comment]
Wurde schon vorgeschlagen, nach ein paar Updates sollte es irgendwann verfügbar sein. 😄

**Comment by ghost** [comment]
Daaanke
