### ISSUE TITLE
Variablen Fehler

### ISSUE THREAD

**Issue by ghost** [tim03we/AdvancedBan#2]
Wenn man jemanden Bant werden im Chat die variablen als {name} z. B. angezeigt

**Comment by tim03we** [comment]
Thanks for your report! I'll take a look at it soon. When exactly does the variable error occur, so in which execution?

**Comment by ghost** [comment]
if i type /ban <name> <id> the output is
{player} has been banned for {reason}

**Comment by tim03we** [comment]
Okay, thanks! I'll check this out soon.

**Comment by tim03we** [comment]
Fixed. :P
