### ISSUE TITLE
Licensfrage

### ISSUE THREAD

**Issue by ghost** [tim03we/AdvancedBan#3]
Darf ich den Code des Plugins ändern, also um eigene Bangründe hinzuzufügen? (Natürlich lasse ich dich als Autor stehen)

**Comment by champmq** [comment]
Erstell ein Fork

**Comment by tim03we** [comment]
Dies kannst du gerne tun, solange du das Plugin nicht als dein eigenes ausgibst.

**Comment by ghost** [comment]
Ich weiß das kommt jetzt dumm aber was ist ein Fork? Bin erst neu bei PHP und Plugins! BTW ich weiß das fork gabel heißt

**Comment by champmq** [comment]
Ein fork ist sogesagt eine Kopie von einem plugin damit kannst du das plugin ändern ohne das du issues oder so erhälst auf github .

**Comment by ghost** [comment]
Ok danke,
Kann ich es dann auch auf youtube hochladen und dann aber mit den link zu deiner poggit seite reinmache

**Comment by tim03we** [comment]
Ja kannst du. :)

**Comment by ghost** [comment]
Danke
